### ISSUE TITLE
fetch api is not being intercepted by zones

### ISSUE THREAD

**Issue by IgorMinar** [angular/zone.js#108]
https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API

example usage:
```
fetch('foo.json').then(function(response) { return response.json() });
```

**Comment by vicb** [comment]
It should be as it returns a Promise.

**Comment by vicb** [comment]
Just submitted #112 to check what browsers need a patch.

Would be interesting to know if the browsers are supposed to return a `new global.Promise()` (ie is it a browser bug ?). Otherwise we'll probably need to patch more than fetch: `Response.text()` and the like

**Comment by vicb** [comment]
@IgorMinar from my tests the issue seems to be that `fetch()` does not instantiate a `window.Promise` but a (derived of) `Promise`.

That means that our monkey patch on `window.Promise` is not taken into account. This also means that would probably should patch all functions that returns a `Promise`.

Is this possible for you to check with the Chrome team if that's the current behavior is the desired one ?

**Comment by radotzki** [comment]
This bug is reproducible from zone.js 0.6.0.
My workaround:
```javascript
return new Promise((resolve, reject) => {
  return window
    .fetch(url, fetchOptions)
    .then((response) => resolve(response.json()));
});
```
