### ISSUE TITLE
window.onerror signature is incorrect

### ISSUE THREAD

**Issue by jbedard** [angular/zone.js#1108]
The `window.onerror` handler has [a different method signature](https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onerror#window.onerror) compared to all other `*.on*` event methods. When ZoneJS wraps `window.onerror` it changes the signature to be the standard handler signature instead of the `window.onerror` specific signature.

http://embed.plnkr.co/jiclV3raUVIhlz3uQ3IM/

**Comment by JiaLiPassion** [comment]
@jbedard , thank you for posting the issue, I will fix this one.

**Comment by JiaLiPassion** [comment]
@Matrosskin, sorry I don't know the exact release date, I can create a temp release branch if you want.

**Comment by Matrosskin** [comment]
@JiaLiPassion what it will mean for us? it will be a branch which almost ready for release - it will be a copy of the current state of the master, so new changes in master will not affect this branch until the exact release will be scheduled, correct? So basically we can just always checkout the exact commit instead of create temp release branch? Or relase branch means something bigger than just creating the branch?

**Comment by JiaLiPassion** [comment]
@Matrosskin, the master branch will have the newest source code, but the `dist` folder will not be updated, so even you point your `package.json` to master, you will still use the 0.8.26 version zonejs. 
So I can create a temp release branch which will also update the `dist` folder.

**Comment by dottodot** [comment]
Any idea when this fix will be released?
