### ISSUE TITLE
bug: Angular 1.x App with Zone.js

### ISSUE THREAD

**Issue by hkyip** [angular/zone.js#29]
I am trying to experimenting Zone.js with Angularjs. I have problem using `Zone.longStackTraceZone` in my controllers.  

Here is the flow of my test app.

``` js
function startApp() {
  angular.bootstrap( document, ['app']);
}
....
```

document ready 

``` js
var myZone = zone.fork(Zone.longStackTraceZone).run (  startApp)
```

I also have a "Bind Error / Cause Error" example on my page,  and I was able to capture the long stack trace.

However in my angular controller, I purposely throw a new Error on a ngclick,  I can just see the normal angular exception in my console, any ideas?

**Comment by RobertjanTuit** [comment]
Any updates on using zone.js in this way with angular 1.4?

**Comment by matthewjh** [comment]
Pretty sure this is because angular's `$exceptionHandler` eats uncaught exceptions inside `$apply`'d functions/expressions and logs them to the console. This means they will never reach zone.

In my Angular 1.x app that I'm using with zone, I'm decorating `$exceptionHandler` to rethrow errors.

**Comment by RobertjanTuit** [comment]
Thanks! Would you mind sharing an example of how you are doing the decoration?

Sent from my iPhone

On Sep 9, 2015, at 9:12 AM, Matthew Hill <notifications@github.com<mailto:notifications@github.com>> wrote:


Pretty sure this is because angular's $exceptionHandler eats uncaught exceptions inside $apply'd functions/expressions and logs them to the console. This means they will never reach zone.

In my Angular 1.x app that I'm using with zone, I'm decorating $exceptionHandler to rethrow errors.

**Comment by matthewjh** [comment]
Sure. Off the top of my head:

````javascript
module.config(function($provide) {
  $provide.decorator('$exceptionHandler', function($exceptionHandler) {
       return function(error, cause) {
            $exceptionHandler(error, cause);
            throw error;
       };
   });
});
````

**Comment by RobertjanTuit** [comment]
Thank you sir! :)

Sent from my iPhone

On Sep 9, 2015, at 9:33 AM, Matthew Hill <notifications@github.com<mailto:notifications@github.com>> wrote:


Sure. Off the top of my head:

module.config(function($provide) {
  $provide.decorator('$exceptionHandler', function($exceptionHandler) {
       return function(error, cause) {
            $exceptionHandler(error, cause);
            throw error;
       };
   });
});

**Comment by gaui** [comment]
Why hasn't this been addressed? I'm currently using zone.js 0.5.15 (outdated) to be able to use Fetch API instead of $http in my Angular 1.x app but trigger the digest cycle after multiple asynchronous operations. I haven't been successful using the new API, so I would like some guidance.

What I'm doing is the following:

```
// Zone addon, so it wraps the promise chain in one "zone" and
// executes some arbitrary task (in this case rootScope digest run)
// after the promise chain.

const scopePrototype = $rootScope.constructor.prototype;
const originalApply = scopePrototype.$apply;
const zoneOptions = {
    afterTask: function afterTask() {
        try {
            $rootScope.$digest();
        } catch (e) {
            $exceptionHandler(e);
            throw e;
        }
    }
};

scopePrototype.$apply = function $applyFn() : void {
    // tslint:disable-next-line:no-var-self
    const scope = this;
    const applyArgs = arguments;

    window.zone.fork(zoneOptions).run(() => {
        console.log('Running zone');
        originalApply.apply(scope, applyArgs);
    });
};
```
