### ISSUE TITLE
zone.js breaks GWT code

### ISSUE THREAD

**Issue by zhy2002** [angular/zone.js#314]
From 0.6 zone.js' wrapper for setTimeout and setInterval returns a task object rather than the integer value. This breaks GWT timer related classes because GWT tries to convert the object to integer to match the java function signature.
Tested in GWT 2.7.

**Comment by pkozlowski-opensource** [comment]
This is pretty severe since from what I can understand we are easily breaking timers cancellation functionality. Is using `zone.data.handleId` an acceptable work-around?

**Comment by pkozlowski-opensource** [comment]
Hmm, actually, scratch my above comment - it looks like things are canceled properly anyhow: https://plnkr.co/edit/lvHw8NQnPW5e1Z4gar1a?p=preview

**Comment by pkozlowski-opensource** [comment]
`setTimout` also behaves properly: https://plnkr.co/edit/k6u7EbIMtBgCmoHyCxrQ?p=preview

Maybe `clearTimout` / `clearInterval` are patched to properly clear timers?

In any case it is not an issue for me any more.

**Comment by vicb** [comment]
@pkozlowski-opensource I think you're not answering the question here (ie return type).

**Comment by pkozlowski-opensource** [comment]
@vicb oh, I agree that the current behaviour is less than ideal. I was just commenting that the current behaviour is not an immediate problem for _me_.

**Comment by recunius** [comment]
This is still a problem for me. Is there any plans to support ZoneJS and GWT together?

For my use case we have a legacy GWT app that we are trying to slowly transition to Angular and this issue is causing strange behavior with GWT-RPC results. It appears that Integer objects within the return results are being changed to ZoneTask objects if the number matches the handleId.

**Comment by JiaLiPassion** [comment]
@recunius , I will make a PR to let `setTimeout` return original id.
