### ISSUE TITLE
Error when using Ripple emulator

### ISSUE THREAD

**Issue by tlancina** [angular/zone.js#335]
Ripple patches XMLHttpRequest to implement a proxy for cross domain requests, which causes zone to throw `TypeError: Cannot set property XMLHttpRequest of #<Window> which has only a getter`.

This is an issue for Visual Studio users building for Cordova, as it appears the only non-simulator target in VS2015 is Ripple.

To reproduce:

``` bash
npm install -g ripple-emulator
git clone https://github.com/angular/quickstart && cd quickstart
npm install
npm run tsc
ripple emulate
```

Not sure if this is a case zone should explicitly support, but wanted to at least make note of the issue, as it affects Ionic users using Visual Studio.

**Comment by TimBarham** [comment]
Some additional info: Ripple patches a bunch of built-in objects to provide simulation support (and, in the case of XHR, a proxy to support cross domain posts). It does this using `Object.defineProperty()`, and only defines a getter, not a setter.

This breaks zone.js, which patches build-in objects by setting them directly (resulting in the above error).

This can likely be fixed in Ripple by providing a setter in the `Object.defineProperty()` call. However, it may be worth zone.js using `Object.defineProperty()` to patch built-in objects rather than setting them directly (that would avoid situations like this, but maybe there is a good reason it doesn't do it that way).

**Comment by JiaLiPassion** [comment]
this should work now.
