### ISSUE TITLE
Does not work as an npm module

### ISSUE THREAD

**Issue by kornelski** [angular/zone.js#364]
[package.json contains](https://github.com/angular/zone.js/blob/bf77fbbbf9fe5b7a1c620394c776557502bdf878/package.json#L5,L6): 

``` js
  "main": "dist/zone-node.js",
  "browser": "dist/zone.js",
```

which points to a Webpack-compiled files, which _are not CommonJS module files_ and do not export anything.  This is because Webpack-built bundles are reduced to be fully encapsulated vanilla JS files, and not CJS modules.

The effect of this is that `require('zone.js')` in Node does nothing — returns `{}` instead of Zone's public symbols. Similarly when `require('zone.js')` is used in 3rd party's Webpack build, it will end up running Webpack runtime inside Webpack runtime, instead of importing the module.

> ```
> $ node
> require('zone.js')
> {}
> require('zone.js').Zone
> undefined
> ```

The `main` and `browser` fields must point to CJS modules that do _not_ have Webpack runtime, and have `module.exports = …` statements instead.

**Comment by jmlopez-rod** [comment]
Exactly, similar issue: https://github.com/angular/zone.js/issues/362

**Comment by AepKill** [comment]
`javascript
require('zone.js');
console.log(Zone ); // => { [Function: Zone]
current: [Getter],
  currentTask: [Getter],
  __symbol__: [Function: __symbol__] }
`

**Comment by jmlopez-rod** [comment]
@AepKill , you are missing the point, we should be able to do `var zone = require('zone.js');` like any other package in npm. You don't see [lodash](https://lodash.com/) being used like this do you?

```
require('lodash');
console.log(_);
```

**Comment by nasooz** [comment]
@pornel In node.js, to be able to do `var something = require('something');`, we need to have something like `module.exports = something;` in the respective module.

I had a very quick look at the code and I couldn't find anything relevant. I might be missing something but is zone.js designed to be used in node at all?

**Comment by jmlopez-rod** [comment]
@nasooz , module bundlers like webpack and browserify can use the require syntax to know what modules to include in the bundle.

**Comment by nasooz** [comment]
@jmlopez-rod, thank you for your response but I obviously need to educate myself further because I have only very little experience with browserify and as a result I don't quite understand what you're saying (entirely my bad). I believed that browserify was used to package npm modules for the browser but your response suggests that there is more to it, if I understand it correctly. 

Anyway, do you think you could recommend an article or something to get me started on zone.js with node?

**Comment by jmlopez-rod** [comment]
@nasooz , I would suggest to look at some article that uses webpack. Looking around I found this page https://web-design-weekly.com/2014/09/24/diving-webpack/ that has a sample git repo: https://github.com/web-design-weekly/basic-webpack. What you can do is simply try to play around with it and try to include other npm modules in there and see how webpack puts them in the generated file `dist/bundle.js`. Each file gets assigned a unique id. In this way every time you use `require('some_module')` webpack replaces the string by something like `webpack_require(#)` where `#` is the unique id. I suggest to try it out and play with `lodash` to see how things should work.

**Comment by nasooz** [comment]
@jmlopez-rod, Thank you very much mate! Much appreciated indeed.

**Comment by nasooz** [comment]
@pornel, I did a little bit of digging and found out that `require('zone.js')` actually creates a member in the `global` object called Zone. In other words, code like:
```
require('zone.js');
Zone.current.fork({ ... }).run(function () { ... });
```
should work in node.js. It works for me at least.

The way I see it, your attempt `require('zone.js').Zone` wouldn't work because the module doesn't export a Zone.

On a different note, I still haven't been able to get the hooks working but that's not a critical issue for me at this stage.

Hope this helps.

**Comment by watashiSHUN** [comment]
@nasooz I tried with your code, but it does not work: [stackoverflow link](http://stackoverflow.com/questions/39563213/using-zone-js-hooks-in-node/40798177#40798177)
