### ISSUE TITLE
Zone.js Performance drag with Core.js polyfill & Webpack

### ISSUE THREAD

**Issue by zackarychapple** [angular/zone.js#376]
After switching to the webpack branch for the Angular CLI I noticed a huge performance hit. 

My page that use to take 1.5 seconds to load now takes about 12 seconds to load.  It seems the vast majority of the time is idle time.  The only change, besides switching to webpack that I saw was the introduction of core.js bringing in reflection from es7.

<img width="1477" alt="screen shot 2016-07-14 at 12 03 22 am" src="https://cloud.githubusercontent.com/assets/2133184/16840287/cd516b3e-49a1-11e6-9692-9bd923cddf81.png">

![screen shot 2016-07-14 at 8 24 44 am](https://cloud.githubusercontent.com/assets/2133184/16840301/d9c735ce-49a1-11e6-8dee-4e22c13cc6d1.png)

<img width="755" alt="screen shot 2016-07-14 at 8 22 45 am" src="https://cloud.githubusercontent.com/assets/2133184/16840296/d4c6f244-49a1-11e6-9767-104d00dc57af.png">

**Comment by gdi2290** [comment]
We were able to reproduce the problem using the old polyfill method es6-shim and reflect-metadata. The issue was zone.js not being loaded before other 3rd party scripts. There might be an iframe auth issue with zone.js or at least a common gotcha. Bootstrapping after the document is ready, which is best practice, was something else that cut the boot time in half. The change detection running after 10 seconds was due to a setInternal
