### ISSUE TITLE
Zone.js Perf w/ external libs like ThreeJS

### ISSUE THREAD

**Issue by amcdnl** [angular/zone.js#393]
Zone.js triggers zone re-runs on every `setTimeout` as I understand. In my application, we use ThreeJS & D3 which does these type of operations quite frequently. Since ThreeJS does GPL animations/etc the zone re-triggers cause un-ideal performance.

Below you can see the difference between a force directed layout distribution tick with and without Zone.js

![zone](http://content.screencast.com/users/amcdaniel22/folders/Snagit/media/4ba0188d-4dfc-4914-8f80-a762efb5d95d/2016-08-09_18-35-16.png)

I basically had to go through every entry point to any type of interaction w/ the threejs component and add the `this.ngZone.runOutsideAngular(() => { ... })`. I also had to ensure I had `changeDetection: ChangeDetectionStrategy.OnPush` set on the container component.

This is rather un-ideal as now my component that was decoupled from Angular is now coupled due to having to call that function at every entry point. Additionally, others will likely encounter this and not realize root issue.

Given the monkey patching going on, I'm not sure the best approach to solve this. Perhaps some type of 'exclude' registration on a object?

**Comment by Namek** [comment]
Looks similiar to what I've just found out about:

(see my answer to the topic) http://stackoverflow.com/questions/39643062/huge-performance-impact-on-components-host-document-click-angular2/39705497#39705497

I also posted this https://github.com/angular/angular/issues/11857 but response felt rather harsh.

**Comment by amcdnl** [comment]
I'm not sure this is related, the setTimeout call is out of my control. 

Listening to mouse click on the document will always be pricey hit. I'd recommend hooking up a renderer listener manually only when you need it - https://angular.io/docs/js/latest/api/core/index/Renderer-class.html

**Comment by Namek** [comment]
> I'm not sure this is related, the setTimeout call is out of my control.

@amcdnl Looks like you read question on SO and not the answer.

To simplify, instead of simply doing this code:

```
ngAfterViewInit() {
    document.addEventListener('click', evt => this.evtClickHandler)
}
```

Now I have to do this:
```
constructor(zone: NgZone) {
}

ngAfterViewInit() {
    this.zone.runOutsideAngular(() => {
        document.addEventListener('click', evt => this.offClickHandler(evt))
    })
}
```

@amcdnl Is this not related?

**Comment by mhevery** [comment]
1. This is really a Angular2 issue rather than zone.js issue. `this.ngZone.runOutsideAngular(() => { ... })` is Angular2 API not zone.js API.
2. Once zone.js is loaded all code runs in a zone. So the fact that running outside of the Angular zone (using `this.ngZone.runOutsideAngular(() => { ... })`) fixes the issue implies that it is not a zone.js performance problem but Angular 2 problem.
3. The fact that Angular intercepts all setTimeouts is by design. Yes in some cases it means that we over-render which causes perf issues, but in wast majority of cases you do want to run change detection at the end of `setTimeout`. And for those cases where you don't want to we provide the `runOutsideAngular` API for just such a purpose.

**Comment by amcdnl** [comment]
@mhevery - Whats the appropriate approach given my scenario? Are you going to be logging a Angular bug?

**Comment by mhevery** [comment]
I think the correct approach is to trigger rendering library such as ThreeJS outside of Angular zone, just as you are doing with `this.ngZone.runOutsideAngular(() => { ... })`. If you feel that there are too many places where you have to place this than maybe there may need to be some kind of facade which exits the zone automatically between your application and ThreeJS. 

Your bug is "running Angular 2 change detection too often makes the app slow". I don't think we can make it faster other than to say don't run it too often.  And the reason you are running it too often is that ThreeJS is running inside the AngularZone rather than outside of it. 

I am not sure that there is a bug to be filed.

**Comment by nikkwong** [comment]
I would like to chime in and give my two cents. The overhead zones introduce is typically trivial, but I've been burned multiple times from compute heavy event callbacks on events that are fired frequently like ```scroll``` or ```mousemove```. A notable example of this is ```popperjs```, in [this](https://plnkr.co/edit/FpZl8oODYKsswaffDWoZ?p=preview) example, which creates heavy computations on each scroll event. We can see in this example that the frequency of the scroll event introduces performance/jank problems due to the scroll wrapping introduced by zone. 

That's usually well and good with ```runOutsideAngular```, but as a 3rd party developer I don't have access to the angular runtime and I don't really want to have to care about the framework they are using. I understand that Angular wants to own the execution context of all JS running within the window but from a design philosophy, I can see this being problematic. Imagine B2B applications like intercom relying heavily on these frequent events and being burned when zone introduces performance problems. The problem is that there is no way for 3rd party developers to opt out of this execution context.

I think it would be nice if zone had a static that 3rd party developers could call upon initialization to get access to the native DOM events. This way, we don't have to worry about performance implications derived from the framework the application developer is using. Again, just my two cents. And though this is a corner case, I've written a few compute heavy 3rd party scripts where zone has burned me and I imagine that developers will continue to struggle with it in the future. In the OP's example, it would be pretty much impossible to introduce three.js on the page alongside angular and have good performance. I think there are many cases where angular does not own the entire DOM and we should not have to be bound to its performance setbacks.

**Comment by j2L4e** [comment]
> I think it would be nice if zone had a static like for example Zone.current.runOutsideAngular

it does:

`Zone.root.run(() => { ... });`

**Comment by clark-stevenson** [comment]
What about if you have a class:

    class Test extends Something{
        constructor(private canvas: HTMLCanvasElement){}
    }

And in my Component somewhere I have this:

    ngAfterViewInit(){

       this.canvas = this.canvasRef.nativeElement;

       this.zone.runOutsideAngular(() => {
             this.demo = new Test(this.canvas)
       });

   }

Will `this.demo` and everything within be running outside zone?

It is just that, when I check dev tools, I see a lot of Zone calls on each frame. I think my attempt may be too naive.
