### ISSUE TITLE
consider fetch as a macroTask

### ISSUE THREAD

**Issue by jahtalab** [angular/zone.js#432]
currently fetch is not considered as a task, for some application this is necessary to keep track of all macroTasks

**Comment by vicb** [comment]
could you please expand on this ?

**Comment by jahtalab** [comment]
@vicb , The Fetch API provides an interface for fetching resources (including across the network)  which is similar to XMLHttpRequest API. for example there is a macroTask with 'XMLHttpRequest.send' as source which provides a way to keep track of async tasks.
similarly there can be a 'fetch' macroTask for async fetching of resources. Although since the fetch API returns a promise, the 'fetch' macroTask should be scheduled as soon as `then` is called on that promise. On the other hand you could also consider all 'unresolved' promises as macroTasks,   since they're executed sometime in the future and out of current execution cycle. 

This would be useful for applications that are using fetch API.

Also, I'm already making a fix for this, but my approach is to patch fetch API and attach a property to the promise and in the `promise.then` patch look for this property and schedule a macroTask accordingly. Feedback is appreciated :)

I hope this makes sense, Let me know if you need more info.

**Comment by mhevery** [comment]
Yes, `fetch()` should be a macroTask.

**Comment by blaugold** [comment]
Is this issue still being considered? My use case is the [`apollo-client`](https://github.com/apollographql/apollo-client) and change detection in protractor tests. `apollo-client` uses `fetch` to make requests but protractor can not wait for those requests because only `Promise.then` is scheduled and only after the response has come back. I would need the patched `fetch` to schedule a `microTask` before the original `fetch` implementation is called.

**Comment by CaerusKaru** [comment]
@blaugold This doesn't help for the original issue, but apollo-client v2 has moved to Angular HttpClient instead of fetch, hopefully that fixes your problem.
