### ISSUE TITLE
PR #430 Breaks Stream interface in Node.js

### ISSUE THREAD

**Issue by Artmobile** [angular/zone.js#470]
PR #430  breaks fluent interface nature of **Node.js** Stream:

To reproduce, uncomment `require("zone.js")`. The code will crash because **createInterface** and **on** do not return _self_ which prevents cascading

``` js
//require("zone.js")
const fs = require("fs")

require('readline').createInterface({
  input: fs.createReadStream('/etc/hosts')
}).on('line', function (line) {
  console.log(line)
}).on('close', function () {
  console.log('done')
});
```

**Comment by jakubmal** [comment]
`createInterface` works correctly as it's not patched by Zone, `on` is fixed in the PR.

**Comment by KrauseStefan** [comment]
Is the pull request going to be merged soon?

For others finding this issue, you might have luck with the following workaround, provided you are not using the event integration in node.js

```js
require('zone.js');
var events = require('events');
events.prototype.on = events.prototype.__zone_symbol__addListener;
events.prototype.addListener = events.prototype.__zone_symbol__addListener;
```

I use it myself for now but would really love to get rid of it since, it does disable the integration in the event system.

As a bit of background info, I have this dependency in order for getting angular2 dependency injection to work in my server side typescript.
