### ISSUE TITLE
Newrelic readme note

### ISSUE THREAD

**Issue by jahtalab** [angular/zone.js#512]
Could you please provide more info about this note in the readme: "If you're using newrelic make sure you import newrelic first as it patches global.Promise before zone,js does"

What is the issue exactly?
Can we do something so that zone.js can simply be loaded before any other script? 
It is really hard (and in some cases impossible) to get the order of execution right, when there are special cases. Specially because we need to look for any library that patches `global.Promise`.

**Comment by gdi2290** [comment]
This is just how to the two libraries are designed. They both money-patch globals for their own reason. Meteor also did this in the past so it's just something everyone has to deal with until Zone becomes a standard or if there is a flag introduced into Node that will support Zone.js natively. Newrelic can introduce a zone.js version that takes advantage of zone.js rather than their own system for tracking errors but that's also a lot of development work for no real reason.

**Comment by jahtalab** [comment]
@gdi2290 , 
Thanks for your reply.
So the issue only exist on Node and not on browsers?
Also, Could you please provide more detail why loading Zone.js after newrelic is resolving the issue?

**Comment by gdi2290** [comment]
the same thing happens in browsers. If there is anything patching Promises/setTimeout etc you have to include it before zone.js that way zone.js is able to wrap them for angular to track async calls.

for newrelic they also patch Promises and you can see it here. 
https://github.com/newrelic/node-newrelic/blob/master/lib/instrumentation/promise.js

you can also create an issue with newrelic and ask them more about their lib
