### ISSUE TITLE
ZoneAwareError captureStackTrace Node v7.2.0 not defined

### ISSUE THREAD

**Issue by nakedcity** [angular/zone.js#520]
zone.js@~0.7.2
Nodejs v7.2.0

```
node_modules/depd/lib/compat/index.js:28
  Error.captureStackTrace(obj)

**Comment by JiaLiPassion** [comment]
I have made a PR to fix this, #516.

**Comment by JiaLiPassion** [comment]
It has been fixed, you can use the newest version to test.

**Comment by nakedcity** [comment]
I updated and I'm getting back the error Error.captureStackTrace is not a function

**Comment by JiaLiPassion** [comment]
It is not merged into dist folder yet, so you have to clone the zone.js and build for yourself, if you want, I can provide you a attached file for test.

**Comment by nakedcity** [comment]
I tried your branch did not work is the dist folder also in yours not build?

**Comment by JiaLiPassion** [comment]
The dist folder will not be committed, you should run 
```javascript
gulp build
```

**Comment by nakedcity** [comment]
I will wait till is in dist thanks

**Comment by linusbrolin** [comment]
@JiaLiPassion When do you plan on updating npm with this fix?

As it is right now, I cannot use angular2-universal, specifically angular2-universal-polyfills, because of this bug.
I've tried mapping the path in system.config.js to a copy of the pre-built zone-node.js file you provided in https://github.com/angular/zone.js/issues/515, but cannot get it to work, so for now I would have to make a copy of angular2-universal-polyfills and replace the zone-node.js import.

**Comment by JiaLiPassion** [comment]
sorry, I have permission to update the npm version, please wait a little longer , the pr has been merged, so there should be a minor version update soon.
