### ISSUE TITLE
zone-node does not trigger change detection in Angular-CLI projects since version 1.0.0-beta.20

### ISSUE THREAD

**Issue by DevWurm** [angular/zone.js#533]
I use Angular 2 in Electron and created [this](https://github.com/DevWurm/electron-explorer) little sample app, with version 1.0.0-beta.19-3 of the Angular-CLI. In this case the change detection of data, which are altered through Node core functions (fs.readdir) work absolutely fine, when using the zone-node polyfill.

When I tried to build the same app with version 1.0.0-beta.20-4 of the CLI the change detection did not work at all.
I also built the app for Electron and included the zone-node polyfill, but in contrast to the first time I wrote the app, the data got not updated in the UI, when they were altered (i.e. when changing the directory in the file explorer). 

Both versions use Angular 2.1.

There is a small difference in the behaviour when using the plain zone polyfill:<br>
When using zone-node, the data get displayed the first time after loading the view  (they get fetched the first time in the OnViewInit Lifecycle event). When using zone, they don't.

I have absolutely no idea, what could cause the problem, so I don't know, which information could be necessary. Please ask for additional information, if you have any idea!

**Comment by JiaLiPassion** [comment]
the repo you provide is the correct one, could you provide the package.json of the problematic one?
And please describe how to reproduce the error, so we can look into it. thanks.

**Comment by DevWurm** [comment]
Excuse my incorrect information and the late answer, I will update the original Issue

**Comment by DevWurm** [comment]
I did some more research about the problem:
It works flawlessly with version `1.0.0-beta.19-3` of the CLI
Version `1.0.0-beta.20-1` and `1.0.0-beta.20-2` don't work at all (can't create new projects) and Version `1.0.0-beta.20-3` as well as the latest Version `1.0.0-beta.22-1` work without change detection.
[Here](https://gist.github.com/DevWurm/521c29d7596092c366a6b8d74ec529a8) you have the `package.json` files for `1.0.0-beta.19-3`, `1.0.0-beta.20-3` and `1.0.0-beta.22-1`.

**Comment by JiaLiPassion** [comment]
@DevWurm, Thank you, I will try to debug it.

**Comment by sushantkhanna** [comment]
Any updates on this issue?

**Comment by JiaLiPassion** [comment]
The reason is electron use zone-node, and not patch browser events. and from angular 2.2(maybe), angular will not patch event and reply on zone.js's patch totally, so in new version, it will not work any more.

I will try to make a PR to fix it, it will need a zone.js version can patch both browser and node.

**Comment by sushantkhanna** [comment]
I am sorry. Did not get you.
Are you saying that Angular might not be able to do live reloads on
Electron at all post 2.2?


On 21-Jan-2017 11:16 PM, "JiaLiPassion" <notifications@github.com> wrote:

The reason is electron use zone-node, and not patch browser events. and
from angular 2.2(maybe), angular will not patch event and reply on
zone.js's patch totally, so in new version, it will not work any more.

I will try to make a PR to fix it, it will need a zone.js version can patch
both browser and node.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/angular/zone.js/issues/533#issuecomment-274276473>, or mute
the thread

**Comment by JiaLiPassion** [comment]
@sushantkhanna , I am not familiar with electron, I don't know the detail about live reloads. But I think it is a problem that zone.js can't deal with node and browser and the same time.

the reason that the @DevWurm 's demo not work is from angular 2.2

if electron choose to load zone-node.ts from polyfill.ts 
```javascript
  <li><a (click)="changeDir(entry)">{{entry}}</a></li>
```
the click event will not patched by zone.js 

otherwise if electron choose to load zone.ts from polyfill.ts

```javascript
 readdir(this.currentPath, (err: Error, files: [string]) => {
      if (err) {
        return console.error(err);
      }

      this.entries = ['../'].concat(files);
    });
```
the fs api will not be patched by zone.js

So I think we need a zone-mix.ts to deal with all apis from browser and nodejs.

**Comment by sushantkhanna** [comment]
Makes sense.
Can we start this as a separate project ? Maybe get the Electron folks
involved ?

**Comment by JiaLiPassion** [comment]
@sushantkhanna , I have made a PR to generate a zone-mix.js to fix this specified issue. So with this PR, application can use browser and node API in zone.

> Can we start this as a separate project ? Maybe get the Electron folks
> involved ?

Do you mean make a electron with zone?

**Comment by sushantkhanna** [comment]
No, I meant involving Electron folks to write zone-mix. But since you have
already, then it does not matter.

Awesome and Thanks !!
